Console.WriteLine("Entre com o seu nome completo: ");
string nome = Console.ReadLine();
Console.WriteLine();
Console.WriteLine("Quantos quartos tem na sua casa? ");
int quartos = int.Parse(Console.ReadLine());
Console.WriteLine();
Console.WriteLine("Entre com o preço de um produto: ");
double preco = double.Parse(Console.ReadLine());
Console.WriteLine();
Console.WriteLine("Entre com seu último nome, idade e altura (mesma linha): ");
string[] vetor = Console.ReadLine().Split(" ");
Console.WriteLine();
Console.WriteLine("Nome completo: " + nome);
Console.WriteLine("Número de quartos na casa: " + quartos);
Console.WriteLine("Preço do produto: " + preco + "R$");
Console.WriteLine("Último nome: " + vetor[0]);
Console.WriteLine("Idade: " + vetor[1]);
Console.WriteLine("Altura: " + vetor[2]);
Console.ReadLine();